In [110]:
print("test")

test

In [111]:
import pandas as pd

In [112]:
df = pd.read_excel("/Users/nanaamoako/Library/CloudStorage/OneDrive-AshesiUniversity/Ashesi/Year 2/May 2024 Semester/AI/Week 5/COVID Deaths.xls")

In [113]:
df

,hospital_number,Na,K,k,Clin,hco3std,ventilation,ventilation_mode,HbA1c,Albumin,...,hiv_new_diag,immunodeficiency,tb_1,copd,ckd,hospital_number.1,venti,ag_n,ag,153
0,121265060,131.0,5.6,4.60,96.0,27.5,High Flow,NaN,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,121265060,Non-invasive,7.5,13.1,NaN
1,38461596,128.0,3.1,3.00,98.0,29.4,Other,NaN,6.3,NaN,...,1.0,1.0,2.0,1.0,1.0,38461596,Non-invasive,0.6,3.7,NaN
2,87594446,128.0,3.9,3.20,97.0,29.1,High Flow,NaN,12.1,NaN,...,1.0,1.0,2.0,1.0,1.0,87594446,Non-invasive,1.9,5.8,NaN
3,42450692,135.0,3.9,3.30,114.0,19.1,Other,NaN,NaN,NaN,...,1.0,1.0,2.0,1.0,1.0,42450692,Non-invasive,1.9,5.8,NaN
4,24941833,134.0,4.7,4.10,103.0,28.1,Other,NaN,6.6,NaN,...,NaN,1.0,2.0,1.0,1.0,24941833,Non-invasive,2.9,7.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,89012926,133.0,5.2,5.20,94.0,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,2.0,89012926,Invasive,NaN,NaN,NaN
486,54123211,137.0,5.3,4.21,106.0,NaN,Other,NaN,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,54123211,Non-invasive,NaN,NaN,NaN
487,40583361,140.0,4.1,NaN,99.0,NaN,Intubated,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,40583361,Invasive,NaN,NaN,NaN
488,45449568,NaN,NaN,4.20,NaN,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,45449568,Invasive,NaN,NaN,NaN
489,22215800,136.0,5.6,4.70,NaN,23.9,Intubated,aprv,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,22215800,Invasive,NaN,NaN,NaN

### Drop NAs

In [114]:
# drop NAs
# df.drop(columns=[153], inplace=True)

In [115]:
df

,hospital_number,Na,K,k,Clin,hco3std,ventilation,ventilation_mode,HbA1c,Albumin,...,hiv_new_diag,immunodeficiency,tb_1,copd,ckd,hospital_number.1,venti,ag_n,ag,153
0,121265060,131.0,5.6,4.60,96.0,27.5,High Flow,NaN,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,121265060,Non-invasive,7.5,13.1,NaN
1,38461596,128.0,3.1,3.00,98.0,29.4,Other,NaN,6.3,NaN,...,1.0,1.0,2.0,1.0,1.0,38461596,Non-invasive,0.6,3.7,NaN
2,87594446,128.0,3.9,3.20,97.0,29.1,High Flow,NaN,12.1,NaN,...,1.0,1.0,2.0,1.0,1.0,87594446,Non-invasive,1.9,5.8,NaN
3,42450692,135.0,3.9,3.30,114.0,19.1,Other,NaN,NaN,NaN,...,1.0,1.0,2.0,1.0,1.0,42450692,Non-invasive,1.9,5.8,NaN
4,24941833,134.0,4.7,4.10,103.0,28.1,Other,NaN,6.6,NaN,...,NaN,1.0,2.0,1.0,1.0,24941833,Non-invasive,2.9,7.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,89012926,133.0,5.2,5.20,94.0,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,2.0,89012926,Invasive,NaN,NaN,NaN
486,54123211,137.0,5.3,4.21,106.0,NaN,Other,NaN,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,54123211,Non-invasive,NaN,NaN,NaN
487,40583361,140.0,4.1,NaN,99.0,NaN,Intubated,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,40583361,Invasive,NaN,NaN,NaN
488,45449568,NaN,NaN,4.20,NaN,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,45449568,Invasive,NaN,NaN,NaN
489,22215800,136.0,5.6,4.70,NaN,23.9,Intubated,aprv,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,22215800,Invasive,NaN,NaN,NaN

In [116]:
# df.drop(columns=['ventilation_mode', 'Albumin'], inplace=True)

In [117]:
df

,hospital_number,Na,K,k,Clin,hco3std,ventilation,ventilation_mode,HbA1c,Albumin,...,hiv_new_diag,immunodeficiency,tb_1,copd,ckd,hospital_number.1,venti,ag_n,ag,153
0,121265060,131.0,5.6,4.60,96.0,27.5,High Flow,NaN,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,121265060,Non-invasive,7.5,13.1,NaN
1,38461596,128.0,3.1,3.00,98.0,29.4,Other,NaN,6.3,NaN,...,1.0,1.0,2.0,1.0,1.0,38461596,Non-invasive,0.6,3.7,NaN
2,87594446,128.0,3.9,3.20,97.0,29.1,High Flow,NaN,12.1,NaN,...,1.0,1.0,2.0,1.0,1.0,87594446,Non-invasive,1.9,5.8,NaN
3,42450692,135.0,3.9,3.30,114.0,19.1,Other,NaN,NaN,NaN,...,1.0,1.0,2.0,1.0,1.0,42450692,Non-invasive,1.9,5.8,NaN
4,24941833,134.0,4.7,4.10,103.0,28.1,Other,NaN,6.6,NaN,...,NaN,1.0,2.0,1.0,1.0,24941833,Non-invasive,2.9,7.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,89012926,133.0,5.2,5.20,94.0,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,2.0,89012926,Invasive,NaN,NaN,NaN
486,54123211,137.0,5.3,4.21,106.0,NaN,Other,NaN,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,54123211,Non-invasive,NaN,NaN,NaN
487,40583361,140.0,4.1,NaN,99.0,NaN,Intubated,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,40583361,Invasive,NaN,NaN,NaN
488,45449568,NaN,NaN,4.20,NaN,NaN,Intubated,p-simv,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,45449568,Invasive,NaN,NaN,NaN
489,22215800,136.0,5.6,4.70,NaN,23.9,Intubated,aprv,NaN,NaN,...,2.0,1.0,2.0,1.0,1.0,22215800,Invasive,NaN,NaN,NaN

In [118]:
df.to_csv('output.csv')

In [119]:
pwd

'/Users/nanaamoako/Library/CloudStorage/OneDrive-AshesiUniversity/Ashesi/Year 2/May 2024 Semester/AI/Week 5'

### Assign NAs list to file

In [120]:
with open ('missing values.txt', 'w') as f:
    for col in df.columns:
        missing = df[col].isnull().sum()
        if missing > 245:
            f.write(f"{col}: {missing}\n")

### Use file to drop NAs - automated

In [121]:
with open('missing values.txt', 'r') as file:
    for line in file:
        drop_miss = line.strip().split(':')[0]  # Read each line, strip whitespace
        if drop_miss in df.columns:  # Check if the column exists in the DataFrame
            df.drop(drop_miss, axis=1, inplace=True)

In [122]:
df

,hospital_number,Na,K,k,Clin,hco3std,ventilation,HbA1c,ALT,Basophils,...,hiv_status_1,immunodeficiency,tb_1,copd,ckd,hospital_number.1,venti,ag_n,ag,153
0,121265060,131.0,5.6,4.60,96.0,27.5,High Flow,NaN,52.0,0.02,...,2.0,1.0,2.0,1.0,1.0,121265060,Non-invasive,7.5,13.1,NaN
1,38461596,128.0,3.1,3.00,98.0,29.4,Other,6.3,13.0,0.04,...,2.0,1.0,2.0,1.0,1.0,38461596,Non-invasive,0.6,3.7,NaN
2,87594446,128.0,3.9,3.20,97.0,29.1,High Flow,12.1,42.0,0.05,...,2.0,1.0,2.0,1.0,1.0,87594446,Non-invasive,1.9,5.8,NaN
3,42450692,135.0,3.9,3.30,114.0,19.1,Other,NaN,118.0,0.08,...,2.0,1.0,2.0,1.0,1.0,42450692,Non-invasive,1.9,5.8,NaN
4,24941833,134.0,4.7,4.10,103.0,28.1,Other,6.6,36.0,0.01,...,1.0,1.0,2.0,1.0,1.0,24941833,Non-invasive,2.9,7.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,89012926,133.0,5.2,5.20,94.0,NaN,Intubated,NaN,7.0,0.02,...,1.0,1.0,2.0,1.0,2.0,89012926,Invasive,NaN,NaN,NaN
486,54123211,137.0,5.3,4.21,106.0,NaN,Other,NaN,50.0,0.02,...,1.0,1.0,2.0,1.0,1.0,54123211,Non-invasive,NaN,NaN,NaN
487,40583361,140.0,4.1,NaN,99.0,NaN,Intubated,NaN,2948.0,0.14,...,NaN,NaN,NaN,NaN,NaN,40583361,Invasive,NaN,NaN,NaN
488,45449568,NaN,NaN,4.20,NaN,NaN,Intubated,NaN,NaN,NaN,...,NaN,1.0,2.0,1.0,1.0,45449568,Invasive,NaN,NaN,NaN
489,22215800,136.0,5.6,4.70,NaN,23.9,Intubated,NaN,68.0,0.50,...,NaN,1.0,2.0,1.0,1.0,22215800,Invasive,NaN,NaN,NaN

In [123]:
df.columns = df.columns.astype(str)

In [124]:
df.to_csv('output_dropnas.csv')

In [125]:
df.to_clipboard()

In [126]:
# check if quantitave values exist in columns
#if so, replace them with the median of the column
# if categorical replace with mode

### Transforming the data - pipelines

In [127]:
from sklearn.impute import SimpleImputer
from numpy import int64, float64
from sklearn.pipeline import Pipeline
from sklearn. compose import ColumnTransformer, make_column_selector

In [128]:
cat_pipeline = Pipeline([
        ("impute", SimpleImputer(strategy="most_frequent")),
        # ("standardize", StandardScaler()),
])

In [129]:
quant_pipeline = Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        # ("standardize", StandardScaler()),
])

In [130]:
full_pipeline = ColumnTransformer([
    ('quant', quant_pipeline, make_column_selector(dtype_include=[float64, int64])),    #int, float because quantitave 
    ('cat', cat_pipeline, make_column_selector(dtype_include=object)) #object because categorical values are objects 
])

In [132]:
piped_data = full_pipeline.fit_transform(df)
df = pd.DataFrame(data=piped_data, columns=full_pipeline.get_feature_names_out)

TypeError: 'method' object is not iterable

In [ ]:
imp = SimpleImputer(strategy = ' mean') 
s = imp.fit_transform(df)

### Imputation

## Encoding

### Onehot encoding - OneHotEncoder

### Transform into tensors -> numpy array

### split into training and test sets